import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/page";
import { MenuProvider } from '@/context/MenuContext';

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Kalyan Maison",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}`}>
        <MenuProvider>
          <Navbar/>
          {children}

          <h1>Footer</h1>
        </MenuProvider>
      </body>
    </html>
  );
}
